import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { wrapper } from '../store'
import { fetchCoctails } from '../store/slices/rootSlice'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href="/about">About</Link>
      <Link href="/contact">Contact</Link>

    </div>
  )
}
export default Home

export const getServerSideProps: GetServerSideProps =
  wrapper.getServerSideProps((store) => async (context) => {
    try {      
        await store.dispatch(fetchCoctails());
        return {
          props: null
        };
    } catch (err) {
      return {
        props:null
      };
    }
  });
